
[Desktop Entry]
Name=osliner
Type=X-GNOME-Metatheme
Comment=

Name[en_US]=RadienceOsliner

[X-GNOME-Metatheme]
GtkTheme=RadianceOsliner
MetacityTheme=RadianceOsliner
IconTheme=ubuntu-mono-light
GtkColorScheme=fg_color:#101010101010,bg_color:#d999cf72c3d7,text_color:#1a1a1a1a1a1a,base_color:#ffffffffffff,selected_fg_color:#33332e5628e7,selected_bg_color:#b333a2a88f5c,tooltip_fg_color:#ffffffffffff,tooltip_bg_color:#29a700001d0f
CursorTheme=DMZ-Black
CursorSize=24
NotificationTheme=ubuntu
